apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-course-cluster
  region: us-east-1

fargateProfiles:
  - name: demo
    selectors:
      - namespace: demo
  - name: staging
    selectors:
      - namespace: staging
        labels:
          env: staging
          checks: passed
